### ISSUE TITLE
Manual enter SSH passphrase

### ISSUE THREAD

**Issue by linuxmail** [rundeck-plugins/openssh-node-execution#11]
hi,

instead of using a SSH passphrase storage, I would like to enter the passphrase manual, because we want to make sure, that key and passphrase are not on the same place. We use Hashicorp Vaul t to store the private key, but at the moment, without a passphrase. Later we want, that every user can upload the private key, and has to enter his passphrase to execute the job.

For a different job, we use "Secure Remote Authentication †  Password input..." in combination with jsch SSH plugin, but we want to switch to openssh-node-execution.

Is that possible ?

**Comment by ltamaster** [comment]
Hi @linuxmail ,
With the current version is not possible, maybe we can add it using something like `expect` or moving the plugin to a python script (with `pexpect`)
